version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
    time: "08:00"
  open-pull-requests-limit: 10
  reviewers:
  - leocomelli
  assignees:
  - leocomelli
  ignore:
  - dependency-name: k8s.io/api
    versions:
    - "> 0.17.4, < 1"
  - dependency-name: k8s.io/apimachinery
    versions:
    - "> 0.17.4, < 1"
  - dependency-name: k8s.io/client-go
    versions:
    - "> 0.17.4, < 1"
  - dependency-name: k8s.io/cli-runtime
    versions:
    - "> 0.17.4, < 1"
  - dependency-name: k8s.io/kubectl
    versions:
    - "> 0.17.4, < 1"
  - dependency-name: k8s.io/kubernetes
    versions:
    - "> 1.17.4, < 2"
  - dependency-name: gopkg.in/yaml.v2
    versions:
    - 2.4.0
