name: Build
on: [push, pull_request]
jobs:

  test-build:
    name: Test & Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15.6
      id: go

    - name: Set GOPATH and PATH
      run: |
        echo "GOPATH=$(dirname $GITHUB_WORKSPACE)" >> $GITHUB_ENV
        echo "$(dirname $GITHUB_WORKSPACE)/bin" >> $GITHUB_PATH
      shell: bash

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Update build dependencies
      run: make setup

    - name: Check quality code
      run: make verify

    - name: Test
      run: make test

    - name: Build
      run: make build
